import type { Metadata } from 'next'
import Image from 'next/image'
import splashImage from '../../public/splash.jpg'
import Logo from '@/components/logo'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='grid lg:grid-cols-2 h-screen'>
      <div className='relative hidden lg:block overflow-hidden '>
        <Image
          src={splashImage}
          alt='Women running'
          className='w-full h-full object-cover'
        />
        <div className='absolute inset-0 bg-green-700 mix-blend-multiply'></div>
        <div className='absolute inset-0 p-6 grid place-content-center'>
          <Logo className='text-white h-14' />
          <p className='text-white'>Your personal trainer</p>
        </div>
      </div>
      <div className='relative flex flex-col justify-center align-center p-6'>
        <div className='max-w-sm w-full mx-auto'>{children}</div>
      </div>
    </div>
  )
}
